/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;
//conexion
import com.conexion.Conexion;
import javax.swing.JOptionPane;
//reporte general
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
//reporte parametrizado
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Rogelio Mejía, Kevin Uribe, Jong Yang, Gerson González
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    FormCategoria frmCategoria;
    FormAutor frmAutor;
    FormLibro frmProducto;
    FormReporteProducto frmReporteProducto;
    public Menu() {
        initComponents();
        this.setSize(700, 680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSalir = new javax.swing.JMenu();
        menuCRUD = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        menuAutor = new javax.swing.JMenuItem();
        menuLibro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuReportProveedores1 = new javax.swing.JMenuItem();
        menuReportProductos1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        menuCRUD.setText("CRUD");

        menuCategoria.setText("Categoría");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        menuCRUD.add(menuCategoria);

        menuAutor.setText("Autor");
        menuAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAutorMousePressed(evt);
            }
        });
        menuCRUD.add(menuAutor);

        menuLibro.setText("Libro");
        menuLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLibroMousePressed(evt);
            }
        });
        menuCRUD.add(menuLibro);

        jMenuBar1.add(menuCRUD);

        jMenu1.setText("Reportes");

        menuReportProveedores1.setText("Categorías");
        menuReportProveedores1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReportProveedores1MousePressed(evt);
            }
        });
        jMenu1.add(menuReportProveedores1);

        menuReportProductos1.setText("Libros");
        menuReportProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReportProductos1MousePressed(evt);
            }
        });
        jMenu1.add(menuReportProductos1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        if (frmCategoria == null || frmCategoria.isClosed())
        {
            frmCategoria = new FormCategoria();
            desktop.add(frmCategoria);
            frmCategoria.setVisible(true);
        }
        else
        {
            frmCategoria.setVisible(true);
        }
        frmCategoria.setLocation(30,30);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLibroMousePressed
        if (frmProducto == null || frmProducto.isClosed())
        {
            frmProducto = new FormLibro();
            desktop.add(frmProducto);
            frmProducto.setVisible(true);
        }
        else
        {
            frmProducto.setVisible(true);
        }
        frmProducto.setLocation(30,30);
    }//GEN-LAST:event_menuLibroMousePressed

    private void menuReportProveedores1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportProveedores1MousePressed
         Conexion obj = new Conexion();
         JasperReport reporte;
         try
         {
            obj.conectar();
            //compilar reporte
            reporte = JasperCompileManager.compileReport("src/com/reportes/rptProveedores1.jrxml");
            //visualizar reporte
            JasperPrint jp = JasperFillManager.fillReport(reporte, null, obj.getCon());
            JasperViewer.viewReport(jp, false);
         }
         catch (JRException e)
         {
             JOptionPane.showMessageDialog(null, "Ocurrió un error" + e.getMessage());
         }
         finally
         {
             obj.desconectar();
         }
    }//GEN-LAST:event_menuReportProveedores1MousePressed

    private void menuReportProductos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportProductos1MousePressed
        if (frmReporteProducto == null || frmReporteProducto.isClosed())
        {
            frmReporteProducto = new FormReporteProducto();
            desktop.add(frmReporteProducto);
            frmReporteProducto.setVisible(true);
        }
        else
        {
            frmReporteProducto.setVisible(true);
        }
        frmReporteProducto.setLocation(30,30);
    }//GEN-LAST:event_menuReportProductos1MousePressed

    private void menuAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAutorMousePressed
        if (frmAutor == null || frmAutor.isClosed())
        {
            frmAutor = new FormAutor();
            desktop.add(frmAutor);
            frmAutor.setVisible(true);
        }
        else
        {
            frmAutor.setVisible(true);
        }
        frmAutor.setLocation(30,30);
    }//GEN-LAST:event_menuAutorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAutor;
    private javax.swing.JMenu menuCRUD;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuLibro;
    private javax.swing.JMenuItem menuReportProductos1;
    private javax.swing.JMenuItem menuReportProveedores1;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
